/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthSlackCompleteRouteImport } from './routes/auth.slack.complete'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicSlackEventsRouteImport } from './routes/api/public/slack/events'
import { Route as ApiPublicSlackOauthCallbackRouteImport } from './routes/api/public/slack/oauth/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSlackCompleteRoute = AuthSlackCompleteRouteImport.update({
  id: '/slack/complete',
  path: '/slack/complete',
  getParentRoute: () => AuthRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackEventsRoute = ApiPublicSlackEventsRouteImport.update({
  id: '/api/public/slack/events',
  path: '/api/public/slack/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackOauthCallbackRoute =
  ApiPublicSlackOauthCallbackRouteImport.update({
    id: '/api/public/slack/oauth/callback',
    path: '/api/public/slack/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/auth/slack/complete': typeof AuthSlackCompleteRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/slack/oauth/callback': typeof ApiPublicSlackOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/auth/slack/complete': typeof AuthSlackCompleteRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/slack/oauth/callback': typeof ApiPublicSlackOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/auth/slack/complete': typeof AuthSlackCompleteRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/slack/oauth/callback': typeof ApiPublicSlackOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/auth/slack/complete'
    | '/api/public/slack/events'
    | '/api/public/slack/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/auth/slack/complete'
    | '/api/public/slack/events'
    | '/api/public/slack/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/.lovable/oauth/consent'
    | '/auth/slack/complete'
    | '/api/public/slack/events'
    | '/api/public/slack/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicSlackEventsRoute: typeof ApiPublicSlackEventsRoute
  ApiPublicSlackOauthCallbackRoute: typeof ApiPublicSlackOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/slack/complete': {
      id: '/auth/slack/complete'
      path: '/slack/complete'
      fullPath: '/auth/slack/complete'
      preLoaderRoute: typeof AuthSlackCompleteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/events': {
      id: '/api/public/slack/events'
      path: '/api/public/slack/events'
      fullPath: '/api/public/slack/events'
      preLoaderRoute: typeof ApiPublicSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/oauth/callback': {
      id: '/api/public/slack/oauth/callback'
      path: '/api/public/slack/oauth/callback'
      fullPath: '/api/public/slack/oauth/callback'
      preLoaderRoute: typeof ApiPublicSlackOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthSlackCompleteRoute: typeof AuthSlackCompleteRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSlackCompleteRoute: AuthSlackCompleteRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicSlackEventsRoute: ApiPublicSlackEventsRoute,
  ApiPublicSlackOauthCallbackRoute: ApiPublicSlackOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
